spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    username: root
    password: Password@Jaimini
    url: jdbc:mysql://localhost:3306/kudosemojis
    driver-class-name: com.mysql.cj.jdbc.Driver
server: 
  port: 9001